<a href="https://colab.research.google.com/github/kakarot5suyash/Numpy_Exercises/blob/main/Numpy_Exercise_39.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise - 39
## Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8 and assign to the variable image.

In [1]:
import numpy as np

In [2]:
image = np.random.randint(low = 0, high = 256, size = (200, 300), dtype = np.uint8)
print(image)

[[103 178 185 ... 174  77 174]
 [ 33 141 107 ...  23  85 191]
 [191  88 130 ...  43   3 166]
 ...
 [ 15  57 217 ...  88 230 196]
 [234 249 166 ...  61  43 242]
 [158  75 249 ... 155 170 122]]
