<a href="https://colab.research.google.com/github/kakarot5suyash/Numpy_Exercises/blob/main/Numpy_Exercise_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise - 22
## Using Numpy create the following array:


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```



## Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. Print this variable to the console

In [1]:
import numpy as np

In [5]:
A = np.arange(12).reshape(3, 4)

# Saving array in a text file
np.savetxt('array.txt', A, fmt='%0.2f')




In [6]:
# Loading array from txt file
B = np.loadtxt('array.txt' )
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
