<a href="https://colab.research.google.com/github/kakarot5suyash/Numpy_Exercises/blob/main/Numpy_Exercise_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise - 24
## The following array is given
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```





## Using the slice operator, transform this array into the following:
```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```
## In response, print transformed array to the console.
## Expected Output
```
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
```





In [1]:
import numpy as np

In [2]:
A = np.arange(12).reshape(3, 4)
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
