<a href="https://colab.research.google.com/github/kakarot5suyash/Numpy_Exercises/blob/main/Numpy_Exercise_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise - 21
## Using Numpy create the following array:


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

```



## Save this array to a binary file named 'array.npy' and then load that file back into another variable. Print this variable to the console.

In [1]:
import numpy as np

In [5]:
A = np.arange(12).reshape(3, 4)
np.save('array.npy', A)


In [6]:
B = np.load('array.npy')
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
