<a href="https://colab.research.google.com/github/kakarot5suyash/Numpy_Exercises/blob/main/Numpy_Exercise_38.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise - 38
## Using Numpy create any 3-dimensional array with shape (2, 3, 4) and assign to variable A.

## Expected Result:
```
[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]
 
 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]
```



In [1]:
import numpy as np

In [2]:
A = np.array([[[4, 5, 4, 2],
               [6, 3, 5, 1],
               [5, 2, 1, 2]],
              
              [[7, 2, 3, 1],
               [6, 2, 0, 9],
               [0, 1, 9, 1]]])
print(A)

[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]

 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]
