<a href="https://colab.research.google.com/github/kakarot5suyash/Numpy_Exercises/blob/main/Numpy_Exercise_33.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise - 33
## The following array is given:
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
## Replace elements greater than 10 with a fixed value = 10.0 and print result to the console.



## Expected Result:
```
[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]
```



In [1]:
import numpy as np

In [2]:
A = np.array([[4.99, 3.49, 9.99],[1.99, 9.99, 14.99],[14.99, 2.39, 7.29]])
print(np.where(A > 10.0, 10.0, A))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]
